version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
      - image: circleci/node:9.5.0


    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: npm install
      - run: gsutil cp gs://staging.human-resources-216715.appspot.com/app.yaml .
      - run: gcloud app deploy
