version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/project/gcloud-service-key.json

      - run:
          name: Install Node.js
          command: |
              curl -sL https://deb.nodesource.com/setup_8.x | bash -
              apt-get install nodejs --yes
      - run:
          name: Install yarn
          command: apt-get install yarn --yes

      - run: npm install
      - run: gcloud auth activate-service-account --key-file=gcloud-service-key.json
      - run: gsutil cp gs://staging.${PROJECT_NAME}.appspot.com/app.yaml .
      - run: gcloud config set project ${PROJECT_NAME}
      - run: gcloud app deploy ./app.yaml --project=${PROJECT_NAME} --promote --quiet
