version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk


    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

      - run:
          name: Install Node.js
          command: |
              curl -sL https://deb.nodesource.com/setup_10.x | bash -
              apt-get install nodejs --yes
      - run:
          name: Install yarn
          command: apt-get install yarn --yes

      - run: cd project
      - run: yarn install
      - run: gsutil cp gs://staging.human-resources-216715.appspot.com/app.yaml .
      - run: gcloud app deploy
